<?php 
session_start();
require_once('../libs/dat_bd.php');
require_once('../libs/lib_bd.php');
require_once('../libs/lib_zapatos.php');
conecta_bd($bd,$servidor,$baseDatos,$usuario,$clave);
$existe=existe_user($bd,$_POST['user'],$_POST['pass']);
if($existe){
    $_SESSION['user']=$_POST['user'];
    $_SESSION['pass']=$_POST['pass'];
    header('location:../inicio.php');
}else{
    $_SESSION['error']=true;
    header('location:../index.php');
}
?>